---
version: "2.0"

services:
  web:
    image: scarruthers/engineering-docs:24
    expose:
      - port: 80
        accept:
          - "akashengineers.xyz"
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"   
      pricing:
        web:
          denom: uakt
          amount: 10000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
